// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXLmGrmLuI_JVj02UYC75xk93B0kOHPEE',
    appId: '1:1089320080302:web:b6f405bc59be1af3bdae3f',
    messagingSenderId: '1089320080302',
    projectId: 'chat-app-397b0',
    authDomain: 'chat-app-397b0.firebaseapp.com',
    storageBucket: 'chat-app-397b0.appspot.com',
    measurementId: 'G-93LSD033ZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOySLY-G1hUtNl6i5sVqt671ZlFKUaTLA',
    appId: '1:1089320080302:android:dfd3a0493efdb0b2bdae3f',
    messagingSenderId: '1089320080302',
    projectId: 'chat-app-397b0',
    storageBucket: 'chat-app-397b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCbRjlsy1tZ3c3U5OFl_Hyej5PXOntxWs',
    appId: '1:1089320080302:ios:7b7a50aa23acf7ebbdae3f',
    messagingSenderId: '1089320080302',
    projectId: 'chat-app-397b0',
    storageBucket: 'chat-app-397b0.appspot.com',
    iosClientId: '1089320080302-c01dlrd28771223189i04b1bjup7fbvf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCbRjlsy1tZ3c3U5OFl_Hyej5PXOntxWs',
    appId: '1:1089320080302:ios:2cca8ea7d69a0578bdae3f',
    messagingSenderId: '1089320080302',
    projectId: 'chat-app-397b0',
    storageBucket: 'chat-app-397b0.appspot.com',
    iosClientId: '1089320080302-jquitr7rsf81pne9b9q8a7aldnanrpfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
